# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._operations import Operations
from ._operations import ResourcePoolsOperations
from ._operations import ClustersOperations
from ._operations import HostsOperations
from ._operations import DatastoresOperations
from ._operations import VCentersOperations
from ._operations import VirtualMachineTemplatesOperations
from ._operations import VirtualNetworksOperations
from ._operations import InventoryItemsOperations
from ._operations import VirtualMachineInstancesOperations
from ._operations import VmInstanceHybridIdentityMetadataOperations
from ._operations import VMInstanceGuestAgentsOperations

from ._patch import __all__ as _patch_all
from ._patch import *  # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk

__all__ = [
    "Operations",
    "ResourcePoolsOperations",
    "ClustersOperations",
    "HostsOperations",
    "DatastoresOperations",
    "VCentersOperations",
    "VirtualMachineTemplatesOperations",
    "VirtualNetworksOperations",
    "InventoryItemsOperations",
    "VirtualMachineInstancesOperations",
    "VmInstanceHybridIdentityMetadataOperations",
    "VMInstanceGuestAgentsOperations",
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()
